CUDA_VISIBLE_DEVICES="0" python3 src/train_llama3.py \
    --model_name_or_path /Models/Meta-Llama-3.1-8B-Instruct \
    --model_type LLM \
    --conv_template_name llama-3 \
    --data_dir ./data/train/ \
    --train_filename train.jsonl \
    --bf16 True \
    --output_dir ./outputs/Meta-Llama-3.1-8B-Instruct \
    --num_train_epochs 2 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "no" \
    --save_strategy "epoch" \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --report_to tensorboard